  - fail:
      msg: "Only RHEL is supported"
    when: ansible_distribution != "RedHat"

  - fail:
      msg: "Major Version must be 7 or 8"
    when: ansible_distribution_major_version != "7" and ansible_distribution_major_version != "8"
