#!/bin/bash

# (C) Copyright IBM Corporation 2020
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

exit_code=1

output=$(dspmq -m $1 -n 2>/dev/null)
if [[ $? -eq 0 ]]
then
    status=$(echo $output | sed 's/.*STATUS(\(.*\))/\1/')
    if [[ $status == "RUNNING" ]]
    then
        exit_code=0
    fi
fi

exit ${exit_code}
