    - name: Install createrepo_c
      package:
              name: "createrepo_c.x86_64"
              state: installed

    - name: Create repodata for prereqs
      command:
              chdir: "/var/tmp/MQ_{{ mq_release }}/MQServer/Advanced/RDQM/PreReqs/el8"
              cmd: createrepo_c .
      when: ansible_distribution_major_version == "8"

    - name: Create local yum repo for prereqs
      yum_repository:
              name: RDQM
              description: "IBM MQ {{ mq_release }} x86_64 RDQM"
              baseurl: "file:///var/tmp/MQ_{{ mq_release }}/MQServer/Advanced/RDQM/PreReqs/el8"
              gpgcheck: no
      when: ansible_distribution_major_version == "8"

    - name: Install semanage
      package:
              name: policycoreutils-python-utils
              state: present

    - name: Add exclude line to existing repository
      lineinfile:
        path: "{{ appstream_repo_file }}"
        insertafter: "{{ appstream_repo_id }}"
        line: exclude=cluster* corosync* drbd kmod-drbd libqb* pacemaker* resource-agents*
