---
- hosts: all
  strategy: free

  tasks:
    - assert:
        that:
          - groups['client'] | length >= 1

    - include_role:
        name: client-os

    - name: Install tar command
      yum:
        name: "{{ packages }}"
        state: latest
        lock_timeout: 180
      vars:
        packages:
          - tar

    - name: Copy MQ Client image
      copy:
              src: "{{ mq_client_image }}"
              dest: "{{ mq_client_image }}"

    - name: Create directory for MQ image
      file:
        path: "/var/tmp/MQ_{{ mq_release }}"
        state: directory

    - name: Unarchive the MQ Client image
      unarchive:
        src: "{{ mq_client_image }}"
        dest: "/var/tmp/MQ_{{ mq_release }}"
        remote_src: yes

    - name: Create local yum repo for MQ Client
      yum_repository:
              name: MQ
              description: "IBM MQ {{ mq_release }} x86_64 Client"
              baseurl: "file:///var/tmp/MQ_{{ mq_release }}/MQClient"
              gpgcheck: no

    - name: Install MQ Client
      yum:
        name: "{{ packages }}"
        state: latest
        lock_timeout: 180
      vars:
        packages:
          - MQSeriesClient
          - MQSeriesSamples
          - MQSeriesSDK

    - name: Create mquser user
      user:
              name: mquser
              password: "{{ mquser_password }}"

    - name: Set MQ installation as the primary installation
      command: /opt/mqm/bin/setmqinst -i -p /opt/mqm

    - name: Create run_rdqmget
      template:
        src: run_script.j2
        dest: /home/mquser/run_rdqmget
        owner: mquser
        group: mquser
        mode: 0755
      vars:
        IP1: "{{ hostvars[groups['rdqm'][0]].ansible_host }}"
        IP2: "{{ hostvars[groups['rdqm'][1]].ansible_host }}"
        IP3: "{{ hostvars[groups['rdqm'][2]].ansible_host }}"
        PORT: 1414
        executable: rdqmget

    - name: Create run_rdqmput
      template:
        src: run_script.j2
        dest: /home/mquser/run_rdqmput
        owner: mquser
        group: mquser
        mode: 0755
      vars:
        IP1: "{{ hostvars[groups['rdqm'][0]].ansible_host }}"
        IP2: "{{ hostvars[groups['rdqm'][1]].ansible_host }}"
        IP3: "{{ hostvars[groups['rdqm'][2]].ansible_host }}"
        PORT: 1414
        executable: rdqmput

    - include_role:
        name: client-el
